### ISSUE TITLE
原始数据类型【Null 和 Undefined】这里有问题 

### ISSUE THREAD

**Issue by chaihongjun** [xcatliu/typescript-tutorial#104]
原文中
> 与 void 的区别是，undefined 和 null 是所有类型的子类型。也就是说 undefined 类型的变量，可以赋值给 number 类型的变量：

```
// 这样不会报错
let num: number = undefined;
````

```
// 这样也不会报错
let u: undefined;
let num: number = u;
```

实际有报错的

> error TS2322: Type 'undefined' is not assignable to type 'number'.

**Comment by xcatliu** [comment]
有没有报错取决于是否设置了 `strictNullChecks`
这里确实需要说明一下，感谢反馈
