### ISSUE TITLE
感觉这里提到tsconfig有点太跳跃

### ISSUE THREAD

**Issue by hu-qi** [xcatliu/typescript-tutorial#122]
https://github.com/xcatliu/typescript-tutorial/blob/master/introduction/hello-typescript.md
![image](https://user-images.githubusercontent.com/17986122/79288822-574fe900-7efa-11ea-84b0-b04dc7c29662.png)

这里好像可以直接设置 --noEmitOnError true禁止生成js文件

新手一枚，这里通过 `tsc .\Hello.ts --noEmitOnError true` 实现，
推荐[compiler-options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by xcatliu** [comment]
感谢建议，准备单独拿一章讲配置～

**Comment by hu-qi** [comment]
感谢，非常期待！
