### ISSUE TITLE
项目中使用到了ts吗？

### ISSUE THREAD

**Issue by guoxiangwen** [xcatliu/typescript-tutorial#13]
看完了，写的很好。想问下作者，项目中使用到了ts吗？哪些场景下使用的。有没有demo学习一下

**Comment by xcatliu** [comment]
以前的团队项目中是使用了 ts 了，使用场景很广泛吧，用 js 的地方都可以用 ts。
现在类型推论已经很成熟了，基本不怎么需要手动指定类型了。
我有个个人项目也用了 ts，可以参考下 https://github.com/xcatliu/mazimd-api

**Comment by guoxiangwen** [comment]
每次安装一个npm package 都要安装对应的@types 都会增加一些额外的工作.。还有就是有没有线上的环境用到了ts。这个好像是你自己的吧

**Comment by xcatliu** [comment]
> 每次安装一个npm package 都要安装对应的@types 都会增加一些额外的工作。

是的，目前还只能这样吧。

> 还有就是有没有线上的环境用到了ts。这个好像是你自己的吧

我之前就职微软的时候，bing.com 是用的 ts。
其他团队可以看看这个问题：[国内有哪些公司的前端团队在生产环境使用typescript？](https://www.zhihu.com/question/37431302)

**Comment by guoxiangwen** [comment]
你们现在还用吗？以后多指教啊

**Comment by guoxiangwen** [comment]
你们现在还用吗？以后多指教啊

**Comment by xcatliu** [comment]
我现在的团队还未使用，因为项目比较老。
不过有计划做新项目的时候会使用

**Comment by xcatliu** [comment]
@guoxiangwen 以后互相学习呀

**Comment by guoxiangwen** [comment]
@xcatliu 有什么开源的东西要搞 可以拉上我。学习一下鹅厂大神的代码

**Comment by xcatliu** [comment]
可以看看 https://github.com/mobi-css/mobi.css 呀，最近在升级到 v3
