### ISSUE TITLE
枚举的概念在 C/C++ 中就有了

### ISSUE THREAD

**Issue by Aladdin-ADD** [xcatliu/typescript-tutorial#15]
https://github.com/xcatliu/typescript-tutorial/blame/master/advanced/enum.md#L227

> 枚举类型的概念来源于 C#。

https://msdn.microsoft.com/en-us/library/whbyts4t.aspx

**Comment by xcatliu** [comment]
我之前是举出 cpp 的例子说明它来源于 cpp 的，不过因为 ts 是 c# 程序员搞出来的东西，所以就改成来源于 c# 了哈😀

**Comment by Aladdin-ADD** [comment]
got! 但我担心有人会误解，加上一些限定可能会严谨一些。e.g.
ts的枚举类型概念直接来源于 C#。

真是严谨而无趣啊。。d=====(￣▽￣*)b

**Comment by xcatliu** [comment]
@Aladdin-ADD 已改，Thanks！
