### ISSUE TITLE
【基础】【联合类型】例子可能有点小问题

### ISSUE THREAD

**Issue by chokingwin** [xcatliu/typescript-tutorial#176]
原文地址：[访问联合类型的属性或方法](http://ts.xcatliu.com/basics/union-types.html#%E8%AE%BF%E9%97%AE%E8%81%94%E5%90%88%E7%B1%BB%E5%9E%8B%E7%9A%84%E5%B1%9E%E6%80%A7%E6%88%96%E6%96%B9%E6%B3%95)

这个例子貌似有点小问题，返回值不能设置成 string 类型

`
function getString(something: string | number): string {
    return something.toString();
}
`

**Comment by xcatliu** [comment]
貌似没有问题呀
https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAcwKZQMpQE4zMgCgGc4BbdACz2QC5EidrEAfRMEUgI1WwEo6GufIgDeAWABQiaYmzoQ2JCXJQq+AHRQ4WIYV4BuSQF9JkoA

**Comment by chokingwin** [comment]
> 貌似没有问题呀
> https://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAcwKZQMpQE4zMgCgGc4BbdACz2QC5EidrEAfRMEUgI1WwEo6GufIgDeAWABQiaYmzoQ2JCXJQq+AHRQ4WIYV4BuSQF9JkoA

OK，没毛病。😅
