### ISSUE TITLE
Global全局变量

### ISSUE THREAD

**Issue by Donkey-Kurt** [xcatliu/typescript-tutorial#18]
你好

在js里想弄个全局变量一般直接global.foo = 'hello';        使用的时候直接this.bar(foo);（这里假设是react native开发）
想重写全局方法会直接 global.console = ()=>{ alert('hello') }      使用的时候直接 console( ); 

想问下用了ts的话应该怎样做？

**Comment by xcatliu** [comment]
```ts
declare global {
    interface Window { MyNamespace: any; }
}

window.MyNamespace = window.MyNamespace || {};
```

可以参考这个讨论：https://stackoverflow.com/questions/12709074/how-do-you-explicitly-set-a-new-property-on-window-in-typescript

**Comment by Donkey-Kurt** [comment]
thanks a lot
