### ISSUE TITLE
ts.xcatliu.com这个地址大纲章节跳转失效

### ISSUE THREAD

**Issue by CourieLiu** [xcatliu/typescript-tutorial#182]
大纲章节点击无效，环境为 Mac 10.15.5，Chrome 版本 83.0.4103.116（正式版本）（64 位）

控制台报错信息为：
> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

> Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://ts.xcatliu.com/introduction/what-is-typescript

**Comment by xcatliu** [comment]
大纲章节是哪一节？

**Comment by CourieLiu** [comment]
左侧所有的章节跳转，包括章节内的“上一章”、“下一章”，还有“黑暗模式切换按钮”，都是点击无效的状态。
右上角Github链接正常，左下角Powered by Pagic正常。

看上面提及的报错信息，我猜测是页面JS模块引用相关的问题。最近几天我和身边同事访问都是这样，就正常访问就可以复现。

**Comment by CourieLiu** [comment]
找到了一个规律，目录点不了的时候，gittalk评论组件也加载不出来

**Comment by xcatliu** [comment]
再试一下，我加了个逻辑，报错时禁用 spa 了
