### ISSUE TITLE
某章节出现不明「?」, 是否为特定意思?

### ISSUE THREAD

**Issue by hezhiming** [xcatliu/typescript-tutorial#2]
**what**
出现不明「?」
```
如果要在报错的时候终止 js 文件的生成，可以在 tsconfig.json 中配置 ？？？ 即可。关于 tsconfig.json，请参阅《？？？》一章。
```

**where**
https://github.com/xcatliu/typescript-tutorial/blob/master/introduction/hello-typescript.md 最后一行

**环境**
* chrome最新
* 时间: 2017_1_16

**Comment by xcatliu** [comment]
感谢指出，抱歉给你带来困扰。

出现？？？的情况是，在写作的初期，没有安排好后面的章节，不知道应该链接到哪儿。
我会在完成所有章节后再校对这种错误。

此处的配置也没有填入，因为打算等把配置的章节写完之后再写。

**Comment by xcatliu** [comment]
已解决
