### ISSUE TITLE
在线预览地址错误

### ISSUE THREAD

**Issue by Yill625** [xcatliu/typescript-tutorial#207]
在线预览地址证书失效  https://ts.xcatliu.com/

**Comment by xcatliu** [comment]
没有失效呀

**Comment by xcatliu** [comment]
![image](https://user-images.githubusercontent.com/5453359/115382180-f8a50580-a206-11eb-9a41-65ceb1555af6.png)

**Comment by Yill625** [comment]
![image](https://user-images.githubusercontent.com/25902472/115382533-67825e80-a207-11eb-9870-4953eca8743d.png)

我这不知道为什么不行

**Comment by xcatliu** [comment]
你用手机访问试试（4g 网络）

**Comment by Yill625** [comment]
> 你用手机访问试试（4g 网络）已经可以了
