### ISSUE TITLE
文档页面显示BUG

### ISSUE THREAD

**Issue by lyc-123** [xcatliu/typescript-tutorial#208]
![image](https://user-images.githubusercontent.com/30492418/115960298-21990380-a543-11eb-907f-e52dc6c5472f.png)
文档右侧列表锚点错误,高亮显示与锚点不对应

**Comment by xcatliu** [comment]
是因为还需要再往下滚一点才会到「在 TypeScript 中使用 ESLint」章节吧

**Comment by lyc-123** [comment]
是,感觉怪怪的
