### ISSUE TITLE
为什么要用接口来定义函数呢？

### ISSUE THREAD

**Issue by xiaoyu-tamu** [xcatliu/typescript-tutorial#21]
下面两种方法不是相等的吗？ 那为什么 会有第一种写法呢？ 第一种方法优势是什么？ 谢谢

####################################################
     Method 1
####################################################
interface CreateArrayFunc {
  <T>(length: number, value: T): Array<T>;
}

let createArray: CreateArrayFunc;
createArray = function<T>(length: number, value: T): Array<T> {
  let result = [];
  for (let i = 0; i < length; i++) {
    result[i] = value;
  }
  return result;
}

####################################################
     Method 2
####################################################
let createArray = function<T>(length: number, value: T): Array<T> {
  let result = [];
  for (let i = 0; i < length; i++) {
    result[i] = value;
  }
  return result;
}

**Comment by xcatliu** [comment]
当需要用到混合类型接口的时候，第一种写法就有用了：

```ts
interface Counter {
    (start: number): string;
    interval: number;
    reset(): void;
}

function getCounter(): Counter {
    let counter = <Counter>function (start: number) { };
    counter.interval = 123;
    counter.reset = function () { };
    return counter;
}

let c = getCounter();
c(10);
c.reset();
c.interval = 5.0;
```

https://www.typescriptlang.org/docs/handbook/interfaces.html#hybrid-types

**Comment by xiaoyu-tamu** [comment]
理解了。谢谢
