### ISSUE TITLE
https://ts.xcatliu.com/打不开

### ISSUE THREAD

**Issue by yuu2lee4** [xcatliu/typescript-tutorial#22]

**Comment by xcatliu** [comment]
ts.xcatliu.com 是部署在 GitBook 上的，可能需要翻墙才能访问。
如果无法打开的话，可以[阅读 GitHub 版](https://github.com/xcatliu/typescript-tutorial/blob/master/README.md)

**Comment by yuu2lee4** [comment]
https://www.gitbook.com/book/xcatliu/typescript-tutorial/details  这个地址能打开

**Comment by yuu2lee4** [comment]
家里又打得开  可能是公司网络做了限制
