### ISSUE TITLE
数组的类型这一节，有个类数组，我有个问题想问下。

### ISSUE THREAD

**Issue by Jiujiale** [xcatliu/typescript-tutorial#222]
https://ts.xcatliu.com/basics/type-of-array.html
```
function sum() {
    let args: {
        [index: number]: number;
        length: number;
        callee: Function;
    } = arguments;
}
```
大佬，抱歉页面自带的Gitalk 登录后一直403，只能来这提问啦。
想问下这个 arguments 是啥？ 上下文也没声明啊， sum也没有参数啊，求解

**Comment by suchanglin** [comment]
> 
arguments是内部部署的，

**Comment by simongfxu** [comment]
JS 默认给每个函数都会提供 arguments 对象。
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/arguments

**Comment by Jiujiale** [comment]
thank you all
