### ISSUE TITLE
建议增加中文 markdown 格式校验的 ci

### ISSUE THREAD

**Issue by hustcc** [xcatliu/typescript-tutorial#34]
中文规范是阮老师的写作规范：[https://github.com/ruanyf/document-style-guide](https://github.com/ruanyf/document-style-guide)

检查工具是我现在在维护的：[lint-md](https://github.com/hustcc/lint-md)

我测试了一下：

![image](https://user-images.githubusercontent.com/7856674/49841268-eeca9680-fdf1-11e8-9507-8c61e4333f0e.png)

如果 ok，我可以发个 pr！

**Comment by xcatliu** [comment]
很赞啊！欢迎 pr！
