### ISSUE TITLE
关于接口任意属性的一点疑问，对象属性不可以是联合类型(string | number)的吗？

### ISSUE THREAD

**Issue by chaihongjun** [xcatliu/typescript-tutorial#36]
`
interface Person {
    name: string;
    age?: number;
    [propName: string]: string;
}
`

上面这个是示例。改成如下:

`
interface Person {
    name: string;
    age?: number;
     [propName:number|string]: number | string;
}
`
就会报错：error TS1023: An index signature parameter type must be 'string' or 'number'.
看报错信息提示 类型必须是string或者 number。
使用联合类型方式就不可以？

**Comment by xcatliu** [comment]
不可以
