### ISSUE TITLE
let num: number = undefined;会报错

### ISSUE THREAD

**Issue by qbrao** [xcatliu/typescript-tutorial#37]
文档中说

![image](https://user-images.githubusercontent.com/18413314/51305950-2c68b200-1a77-11e9-8e49-3606510ebda5.png)

但是在vscode中书写的时候会提示错误，如下：

![image](https://user-images.githubusercontent.com/18413314/51306073-70f44d80-1a77-11e9-9088-2958bac23118.png)

请问下是什么原因

**Comment by xcatliu** [comment]
是不是你设置了严格模式？

**Comment by qbrao** [comment]
没有手动设置，这个跟严格模式有关系？我是写在vue文件中的

![image](https://user-images.githubusercontent.com/18413314/51316182-d6076d80-1a8e-11e9-9a27-c4630e6412e3.png)

**Comment by qbrao** [comment]
> 是不是你设置了严格模式？

没有手动设置，这个跟严格模式有关系？我是写在vue文件中的

![image](https://user-images.githubusercontent.com/18413314/51317736-58922c00-1a93-11e9-8456-1af5d5afa01c.png)

**Comment by xcatliu** [comment]
是因为设置了 `strictNullChecks`
