### ISSUE TITLE
文档最近版本不更新了么

### ISSUE THREAD

**Issue by ruizhengyun** [xcatliu/typescript-tutorial#42]
文档最近版本不更新了么

**Comment by xcatliu** [comment]
可以，欢迎转载~

> 本书采用「保持署名—非商用」创意共享 4.0 许可证。
> 只要保持原作者署名和非商用，您可以自由地阅读、分享、修改本书。
> 详细的法律条文请参见[创意共享](https://creativecommons.org/licenses/by-nc/4.0/)网站。

**Comment by xcatliu** [comment]
最近较忙，但是我也会不定期更新的，比如最近更新了[声明文件](https://github.com/xcatliu/typescript-tutorial/blob/master/basics/declaration-files.md)这一章，篇幅非常大

可以分享，欢迎转载~

> 本书采用「保持署名—非商用」创意共享 4.0 许可证。
> 只要保持原作者署名和非商用，您可以自由地阅读、分享、修改本书。
> 详细的法律条文请参见[创意共享](https://creativecommons.org/licenses/by-nc/4.0/)网站。
