### ISSUE TITLE
泛型约束  extends 报错

### ISSUE THREAD

**Issue by ronffy** [xcatliu/typescript-tutorial#43]
代码在文章中的位置：
进阶 - 泛型 - 泛型约束报错

```ts
interface Lengthwise {
    length: number;
}

function loggingIdentity<T extends Lengthwise>(arg: T): T {
    console.log(arg.length);
    return arg;
}
```

报错`Parsing error: Unexpected token, expected ","`

![image](https://user-images.githubusercontent.com/13896347/55375176-cd76ed00-553d-11e9-8f92-788285a58317.png)

**Comment by xcatliu** [comment]
看截图貌似是 eslint 报错？是否添加了 [`@typescript-eslint/parser`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser) 呢？

**Comment by ronffy** [comment]
parser 用的默认的`react-app`，忘记修改了。
现在改成`@typescript-eslint/parser`就好了。
感谢！
