### ISSUE TITLE
“数组的类型”章节中“用接口表示数组”的一点建议

### ISSUE THREAD

**Issue by GalenSong** [xcatliu/typescript-tutorial#44]
建议：
interface NumberArray {
    [index: number]: number;
}
let fibonacci: NumberArray = [1, 1, 2, 3, 5];

我觉得接口表示的算是一种字面上类数组的结构，这一结构不能用数组的方法遍历，也不具有数组的属性，应该不算是数组。

**Comment by xcatliu** [comment]
感谢建议！
嗯你说的对，其实这个与类数组（Array-like Object）有些类似。
我稍后把这一章改一下，把这块内容讲清楚

**Comment by xcatliu** [comment]
已添加了用接口表示数组的用途
