### ISSUE TITLE
声明文件中的一些小问题

### ISSUE THREAD

**Issue by tfeng-use** [xcatliu/typescript-tutorial#49]
在声明文件-》什么是声明文件，
有这么一句话：
假如仍然无法解析，那么可以检查下 tsconfig.json 中的 files、include 和 exclude 配置，确保其包含了 jQuery.d.ts 文件。
这个例子我不管怎么配置 tsconfig.json ，在使用tsc XXX 在shell中运行的时候都会报错，说找不到对应的函数等等。（以及后面的全局变量的例子都是一样的）。能否给出一个可以完整通过编译的例子包括配置，这样可能会更有利于理解。

**Comment by xcatliu** [comment]
https://github.com/xcatliu/typescript-tutorial/tree/master/examples/declaration-files
这里的例子都是完整的可以运行的
