### ISSUE TITLE
根据任意值章节中未声明类型的变量板块进行代码编写报错

### ISSUE THREAD

**Issue by chunkke** [xcatliu/typescript-tutorial#51]
let something;
something = 'seven';
something = 7;
​
something.setName('Tom');
会报property 'setName' does not exist on type 'number'的错误，但是
let something: any;
something = 'seven';
something = 7;
​
something.setName('Tom');
就不会报错，想问一下是为什么

**Comment by xiaohaiH** [comment]
他默认是取推断出来的值

**Comment by chunkke** [comment]
原来如此，谢谢啦
