### ISSUE TITLE
关于泛型的的描述

### ISSUE THREAD

**Issue by Yang-yibu** [xcatliu/typescript-tutorial#53]
[博客原文地址](https://ts.xcatliu.com/advanced/generics)

根据[官方网站](https://www.tslang.cn/docs/handbook/generics.html)的描述以及结合底下的例子
![image](https://user-images.githubusercontent.com/23130670/58376680-63f5e680-7fa2-11e9-9e72-3aa42f4ef363.png)

我认为应该这样改一下：
```bash
泛型（Generics）是指在定义函数、接口或类的时候，不预先指定具体的类型，
- 而在使用的时候再指定类型的一种特性
+ 而是在使用时才能确定类型，并保证传入的参数类型与返回值类型相同的一种特性。
```

**Comment by xcatliu** [comment]
并不是

> 保证传入的参数类型与返回值类型相同的一种特性。

呀，不一定是要限制返回值的类型呀
