### ISSUE TITLE
原始数据类型关于undefined与null那块的反馈。

### ISSUE THREAD

**Issue by kylsYw** [xcatliu/typescript-tutorial#60]
在实际使用中均会出现错误。
![image](https://user-images.githubusercontent.com/31870300/59592318-64f1e200-9122-11e9-8a2d-b101a428cef2.png)

**Comment by maquannene** [comment]
+ 1

**Comment by xcatliu** [comment]
是因为你在 `tsconfig.json` 中配置了严格模式
