### ISSUE TITLE
null,undefined类型可以互相赋值。

### ISSUE THREAD

**Issue by hp0844182** [xcatliu/typescript-tutorial#65]
例如：
let a:undefined = null;
let b:null = undefined;
静态检查不会报错，是否适合undefined类型可以赋值：null or undefined。  .同理null类型也是一样。
原文描述：
![image](https://user-images.githubusercontent.com/34418758/60267795-9f772e00-991d-11e9-97d1-eadccaec521c.png)

**Comment by richardmyu** [comment]
> 例如：
> let a:undefined = null;
> let b:null = undefined;
> 静态检查不会报错，是否适合undefined类型可以赋值：null or undefined。 .同理null类型也是一样。
> 原文描述：
> ![image](https://user-images.githubusercontent.com/34418758/60267795-9f772e00-991d-11e9-97d1-eadccaec521c.png)

我发现也是这样

**Comment by xcatliu** [comment]
`tsconfig.json` 中配置了 `strictNullChecks` 的话，就不允许互相赋值了
