### ISSUE TITLE
元组篇章的初始化问题

### ISSUE THREAD

**Issue by w1016163827** [xcatliu/typescript-tutorial#70]
let xcatliu: [string, number];
xcatliu[0] = 'Xcat Liu';
xcatliu[1] = 25;

xcatliu[0].slice(1);
xcatliu[1].toFixed(2);

这段代码经过编译后，是这样的。
var xcatliu;
xcatliu[0] = 'Xcat Liu';
xcatliu[1] = 25;
xcatliu[0].slice(1);
xcatliu[1].toFixed(2);
由于并没有把xcatliu改成数组类型，所以无法使用[0]和[1]对其进行赋值，无法找到属性，会报错。望修改。
顺便：作者能给个联系方式吗？

**Comment by xcatliu** [comment]
感谢返回，稍后修复。
可以微信搜 id

**Comment by xcatliu** [comment]
如果设置 `strictNullChecks` 为 `true` 就会报错了
