### ISSUE TITLE
工程->代码检测部分，typescript-eslint-parser 报错

### ISSUE THREAD

**Issue by wfk007** [xcatliu/typescript-tutorial#73]
报错信息如下：

> Error: Failed to load parser 'typescript-eslint-parser' declared in '.eslintrc': Cannot find module 'eslint/lib/util/traverser'

[原仓库](https://github.com/eslint/typescript-eslint-parser) 貌似不维护了，改成了 [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser) 仓库

**Comment by xcatliu** [comment]
在 #83 中跟进
