### ISSUE TITLE
null不能赋值给number类型变量

### ISSUE THREAD

**Issue by GauharChan** [xcatliu/typescript-tutorial#86]
看到教程说，可以把null和undefined赋值给number类型的变量。然后我去试了一下，结果出现警告了，
不能将类型“null”分配给类型“number”。
我typescript的版本是3.6.3

**Comment by xcatliu** [comment]
去掉 `strictNullCheck` 就不会报错了

**Comment by GauharChan** [comment]
好吧，我看到那里就去试代码，没看到下面
