### ISSUE TITLE
大佬，请教个问题，找不到地方询问只好来这里，望见谅！

### ISSUE THREAD

**Issue by blesstosam** [xcatliu/typescript-tutorial#90]
```
import {Context} from 'koa';  // 引入类型定义
router.get('/api', (ctx: Context) => {  // 使用类型定义
  // xxx
});
```
但是eslint还是报错 
```
'Context' is defined but never used  no-unused-vars
```

我不想关闭这条rule，请问怎么解决这个问题？

**Comment by xcatliu** [comment]
在 eslintrc 中配置 `'no-unused-vars': 'off'` 即可

**Comment by blesstosam** [comment]
但是关闭这条检查规则，一般的未使用变量也检查不出来了。。。

**Comment by xcatliu** [comment]
可以用 [`@typescript-eslint/no-unused-vars`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) 这个规则

**Comment by blesstosam** [comment]
谢谢大佬，已解决！
