### ISSUE TITLE
代码检查-在 TypeScript 中使用 TSLint

### ISSUE THREAD

**Issue by LoveNormalDay** [xcatliu/typescript-tutorial#94]
您好，我在阅读您的文章的时候，按照您文中的方法配置好之后，命令行输出
npm run tslint
会提示
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
因为我用的是3.x版本的TypeScript，比如==，他其实在代码中就提示这个错误了，不需要
npm run tslint

**Comment by LoveNormalDay** [comment]
好的，多谢

**Comment by xcatliu** [comment]
已更新代码检查章节

**Comment by LoveNormalDay** [comment]
看到了，多谢提醒
